Homework3
made-mlops-2022/made-mlops-2022-artem_volkov pull request #4
Opened 2022-11-29 18:39 UTC by Artyom1363

Tasks with airflow

2022-11-29 19:44 UTC, Artyom1363 commented
Выполнено:
0. Локально поднят airflow, используя docker compose
1. Реализован dag, который генерирует данные для обучения модели (5 баллов)
Данные записываются в /data/raw/{{ ds }}/data.csv и /data/raw/{{ ds }}/target.csv
2. Реализован dag, который обучает модель еженедельно, используя данные за текущий день. В пайплайне 4 стадии: preprocess, split, train, validatioin (10 баллов)
3. Реализован dag, который использует модель ежедневно (5 баллов)
принимает на вход данные из пункта 1 (data.csv)
считывает путь до модельки из airflow variables 
делает предсказание и записывает их в /data/predictions/{{ ds }}/predictions.csv
4. Все даги реализованы только с помощью DockerOperator (10 баллов)
5. Проведена самооценка (1 балл)
Общая сумма баллов - 31


Фото из airflow
<img width="1440" alt="Снимок экрана 2022-11-29 в 22 41 52" src="http
<img width="1433" alt="Снимок экрана 2022-11-29 в 22 42 37" src="https://user-images.githubusercontent.com/29337222/204632553-8d61699b-d9d0-4efe-a467-e1fc300c6303.png">
s://user-images.githubusercontent.com/29337222/204632484-611801e2-e728-429e-a9b2-8aadb75685b2.png">
<img width="1422" alt="Снимок экрана 2022-11-29 в 22 42 27" src="https://user-images.githubusercontent.com/29337222/204632524-51f184cc-d47f-45d8-bbb8-bb259430aad3.png">
<img width="1207" alt="Снимок экрана 2022-11-29 в 22 42 54" src="https://user-images.githubusercontent.com/29337222/204632585-7c0af763-fd97-431f-a392-5a93b10c7175.png">
<img width="1211" alt="Снимок экрана 2022-11-29 в 22 43 16" src="https://user-images.githubusercontent.com/29337222/204632615-5be65825-19f3-406e-b20c-273b788c974b.png">

<img width="1204" alt="Снимок экрана 2022-11-29 в 22 43 28" src="https://user-images.githubusercontent.com/29337222/204632635-36ea0e94-2ae0-43a2-9d8d-76d108ac4645.png">

2022-12-04 14:08 UTC, bulaevvi requested changes
Приложите общий скриншот со списком всех дагов

2022-12-04 17:06 UTC, Artyom1363 commented
> Приложите общий скриншот со списком всех дагов

Не понял что значит "общий скриншот". Со списком вообще всех? Их 37, приложил скрин с началом. Так же приложил скрин со списком всех активных.
<img width="1440" alt="Снимок экрана 2022-12-04 в 20 02 46" src="https://user-images.githubusercontent.com/29337222/205504817-09d7
<img width="1438" alt="Снимок экрана 2022-12-04 в 20 05 02" src="https://user-images.githubusercontent.com/29337222/205504849-5ed1ce37-cd73-4adc-ac92-ca9a595c932c.png">
589c-bff8-4fcc-87f3-4eb4535cdf8e.png">

2022-12-05 04:14 UTC, bulaevvi commented
> > Приложите общий скриншот со списком всех дагов
> 
> Не понял что значит "общий скриншот". Со списком вообще всех? Их 37, приложил скрин с началом. Так же приложил скрин со списком всех активных. <img alt="Снимок экрана 2022-12-04 в 20 02 46" width="1440" src="https://user-images.githubusercontent.com/29337222/205504817-09d7589c-bff8-4fcc-87f3-4eb4535cdf8e.png"> <img alt="Снимок экрана 2022-12-04 в 20 05 02" width="1438" src="https://user-images.githubusercontent.com/29337222/205504849-5ed1ce37-cd73-4adc-ac92-ca9a595c932c.png">

Верхний скриншот - как раз то, что надо. Только судя по нему, у Вас задания выполнялись со сбоями (красные окружности). По идее если Вы все сделали нормально, то такого не должно быть

2022-12-05 07:33 UTC, Artyom1363 commented
> Верхний скриншот - как раз то, что надо. Только судя по нему, у Вас задания выполнялись со сбоями (красные окружности). По идее если Вы все сделали нормально, то такого не должно быть

Естественно я не с первого раза сделал. Я на скриншотах выше показал что добился чтобы нормально работал (последний запуск на скринах выше).

2022-12-05 09:27 UTC, bulaevvi commented
Надо добиться, чтобы все сработало, и сделать токой общий скриншот, на котором видно, что все даги нормально сработали

2022-12-05 16:06 UTC, Artyom1363 commented
> Надо добиться, чтобы все сработало, и сделать токой общий скриншот, на котором видно, что все даги нормально сработали

А, да, извиняюсь, при при первом (дефолтном) запуске не было данных для inference. При запуске уже из airflow все норм было.
Прикрепляю скриншот, что сейчас все норм запускается
<img width="1430" alt="Снимок экрана 2022-12-05 в 19 03 30" src="https://user-images.githubusercontent.com/29337222/205684148-d26e244d-6e6c-4881-bed9-072e534c33b5.png">

А так же с проблемным inference, который дефолтно запускался неправильно (исправил, добавив данные в папки data/models и data/transformer_model).
<img width="1427" alt="Снимок экрана 2022-12-05 в 19 04 09" src="https://user-images.githubusercontent.com/29337222/205684282-73fb6ac9-4560-4878-8bf0-7b6fe5e7e8e3.png">

2022-12-06 03:39 UTC, bulaevvi approved these changes
Итого 31 балл. Делайте merge

2022-12-06 06:13 UTC, merged